@echo off
echo 🚀 Starting Sentix Bot Test...

echo 📦 Installing Dependencies...
pip install -r requirements.txt

echo 🌐 Installing Playwright Browser...
playwright install chromium

echo 🤖 Running Sentix...
python main.py
pause
